apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  namespace: roboshop
  labels:
    project: personal
    purpose: ingress
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      project: personal
      purpose: ingress
      app: app1
  template:
    metadata:
      labels:
        project: personal
        purpose: ingress
        app: app1
    spec:
      containers:
        - name: app1
          image: anuragbojja/app1:v1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: roboshop
  labels:
    project: personal
    purpose: ingress
    app: app1
spec:
  selector:
    project: personal
    purpose: ingress
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1 
  namespace: roboshop
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:793770371113:certificate/68684e54-2268-4a53-b47c-33abcdedfcd2
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,project=roboshop
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb 
  rules:
  - host: "app1.anuragaws.shop"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app1
            port:
              number: 80
  # - host: "*.foo.com"
  #   http:
  #     paths:
  #     - pathType: Prefix
  #       path: "/foo"
  #       backend:
  #         service:
  #           name: service2
  #           port:
  #             number: 80
---
